#!/usr/bin/env python3
"""Write the archive-gap ledger used by query_archive_gaps.py."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def gap(**kwargs):
    required = [
        "gap_id",
        "referenced_name",
        "referenced_from",
        "project_or_family",
        "probable_source_type",
        "why_it_matters",
        "known_drive_id_if_any",
        "candidate_ledger_match_if_any",
        "status",
        "confidence",
    ]
    missing = [key for key in required if key not in kwargs]
    if missing:
        raise SystemExit(f"gap missing {missing}")
    return kwargs


GAPS = [
    gap(
        gap_id="GAP-S4-MASTER-TIMELINE",
        referenced_name="S4 Master Timeline",
        referenced_from="registry/projects.jsonl roanoke-s4 planning anchor; research/CHRONOLOGY.md; research/empire-city/source-fragment-map-v1.md; Empire City Dev messages 748279131455881360 and 752645676260917248 (URL only)",
        project_or_family="roanoke-s4 / empire-city-operations",
        probable_source_type="campaign timeline",
        why_it_matters="Current body is BCS-000131. This Drive id is no longer a missing file. Revision bodies were not fetched. A schedule is not play.",
        known_drive_id_if_any="1Lk2IkEgh1aHjuUl35g1Huk7oxjNSjhmfsKKaHDL1_K8",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-S5-STYLE-GUIDE",
        referenced_name="S5 style guide",
        referenced_from="research/CHRONOLOGY.md; registry/projects.jsonl roanoke-s5-legends planning anchor 2022-02-13",
        project_or_family="roanoke-s5-legends",
        probable_source_type="internal design guide",
        why_it_matters="Current body is BCS-000132. The three linked documents are BCS-000177, BCS-000178, and BCS-000179. Images remain inside the style-guide DOCX. Revision bodies were not fetched. A same-titled Bodfish Google Site was not captured.",
        known_drive_id_if_any="1fpOQbmy836cs41ewNXcTUdwdfswuOEETqioshQURcm0",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-S5-DM-GUIDE",
        referenced_name="Season 5 Dungeon Master's guide",
        referenced_from="research/CHRONOLOGY.md",
        project_or_family="roanoke-s5-legends",
        probable_source_type="DM procedures",
        why_it_matters="Current body is BCS-000133. It is an outline, not proof the guidance was followed. Revision bodies were not fetched.",
        known_drive_id_if_any="15EqRAkYPaSj8009y_ygsOun3TzKcFoBvcn9Liw7q_MQ",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-S5-CHARGEN-DOC",
        referenced_name="Season 5 character creation",
        referenced_from="research/CHRONOLOGY.md; research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke-s5-legends",
        probable_source_type="internal character-creation draft",
        why_it_matters="Current body is BCS-000145, a 2025-04-14 modification. The April 2023 wording was not recovered. BCS-000109 remains the published site and a different file.",
        known_drive_id_if_any="1O8E_sDKqqqLKIXFQPkgPNuVqtaj368ulC4sJytiDVK8",
        candidate_ledger_match_if_any=None,
        status="PARTIAL_CURRENT_BODY_ONLY",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-S4-CHARGEN",
        referenced_name="S4 Char Gen",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke-s4",
        probable_source_type="character-creation rules",
        why_it_matters="Empire City has a signup sheet and no ingested character-creation document. This is the named Season 4 char-gen file.",
        known_drive_id_if_any="1arW3PfeD6kDTGLdfHGS7_v7oTORCOMkZ3D1R4FuepVY",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-PLAYER-RACE-EDITS",
        referenced_name="Player race edits",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke race design",
        probable_source_type="revision critique",
        why_it_matters="Current edit note is BCS-000135. It is revision context, not proof the later verbatim files kept this wording. Verbatim revision bodies were not fetched.",
        known_drive_id_if_any="11GF5rYImy_jdf7NxAtf5gI-OW2DCTlxjgZCOHLnC3cY",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-TATANKAN-VERBATIM",
        referenced_name="The Tatankan Verbatim",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke-s3 race lore",
        probable_source_type="race verbatim",
        why_it_matters="Current body is BCS-000138. The captured text is the later file state, not a revision sequence.",
        known_drive_id_if_any="1bDpgesAcJxYDr9NkUU3ARQ4wEoW0Aghxx91QYnKL22g",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-PLAYER-RACES-FINAL",
        referenced_name="Player Races Final.pdf",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke race design",
        probable_source_type="player-facing race export",
        why_it_matters="Would show which race revisions were published. Not in the corpus or the candidate ledger.",
        known_drive_id_if_any="1pvXV2yqH_oVtk16i5rRTQFY2KPKllcHg",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-CLERROOK",
        referenced_name="Clerrook Subclass",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="class design, project unresolved",
        probable_source_type="subclass design",
        why_it_matters="Named revision-backed class experiment. Not placed in a campaign container.",
        known_drive_id_if_any="1A0TDh8s4QRhji1b6kFlUOm8b-L47rQ88memK6S5vN8E",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-SETTING-BOOK-HOWTO",
        referenced_name="Creating a setting book for your D&D world, Arcania.",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="Arcania setting",
        probable_source_type="design essay",
        why_it_matters="Explicit design-method writing. Absence leaves setting research with finished lore and not the method note.",
        known_drive_id_if_any="1kQ8hwS44600ZRF-So4vKVi_vM2Q6L2XKvCpMjfMQWTs",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-JARVIS-CLASS",
        referenced_name="jarvis, balance this class",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="class design, project unresolved",
        probable_source_type="balance critique",
        why_it_matters="The title is a correction request. It is the kind of revision evidence later research needs, and it is not ingested.",
        known_drive_id_if_any="1ulVL-K6OWwYlL58U6-Jc8o55UsSapoEesCaTt_Aw_xA",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-DCC-CLASSES",
        referenced_name="Dcc like classes",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="class design, project unresolved",
        probable_source_type="alternate class draft",
        why_it_matters="Named as an alternate class attempt. Not in the corpus, so abandoned class experiments are under-represented.",
        known_drive_id_if_any="1MI1PU-AuXmmli1EGj7XQFPnC5hJi52yE4yepdK1KCJs",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-S5-CRAFTING",
        referenced_name="S5 crafting",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="roanoke-s5-legends",
        probable_source_type="crafting rules",
        why_it_matters="Season 3 and Season 4 crafting are containers. The named Season 5 crafting document is not, so a crafting history would skip Legends.",
        known_drive_id_if_any="1w5QR5YiMsyb3I-sv4NOJlhEIGVrJhhH7gK7EGrSWcKE",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-HOUSE-RULES-2020",
        referenced_name="House rules official release",
        referenced_from="BCS-000046 changelog; BCS-000016 signup question",
        project_or_family="cross-season server rules",
        probable_source_type="player-facing rules",
        why_it_matters="This Drive id is BCS-000134. The captured text is the 2023-04-30 state, not the 2020 wording the Season 3 changelog calls the live release. BCS-000104 remains a different Season 5 site.",
        known_drive_id_if_any="19q9mnafswYmNIUK3DK57O2MPqtSl78M4UcJSfBZfhA8",
        candidate_ledger_match_if_any=None,
        status="PARTIAL_CURRENT_BODY_ONLY",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-AIRSHIP-RULES",
        referenced_name="Airship Rules",
        referenced_from="BCS-000073 source body",
        project_or_family="empire-city-airship-qualification",
        probable_source_type="rules document",
        why_it_matters="The qualification module tells the DM to use this document for ship systems. The flight-school scene shows the drill, not the rules text.",
        known_drive_id_if_any=None,
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-MANTICORE",
        referenced_name="Manticore fight / Bahamut's Folly",
        referenced_from="BCS-000052 week 3 breakdown",
        project_or_family="roanoke-s3-week-operations",
        probable_source_type="main-event module",
        why_it_matters="Week 3 names this as the evening main event and links a document that is not a container.",
        known_drive_id_if_any="1GEt3IcbRsfbRwmXFGk7xYIMQbdnseL-iXb2RqyOJD8Q",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-ARTIFACTS-LIST",
        referenced_name="Knights du Roi Soleil artifacts list",
        referenced_from="BCS-000027 secret-society lore",
        project_or_family="roanoke-s3-secret-society-lore",
        probable_source_type="ending / reward list",
        why_it_matters="The secret-society endings point at this list. The ending procedure is incomplete without it.",
        known_drive_id_if_any="1Tih6QGIHfkUmVcrjVjpAPipsaJ1yH0lHlG1kskPyRi4",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-W5-MAP",
        referenced_name="Week 5 map",
        referenced_from="BCS-000053 link; container BCS-000130",
        project_or_family="roanoke-s3-week5-map",
        probable_source_type="map image",
        why_it_matters="The JPEG is BCS-000130 on main. It has no text layer, and room names are not invented. Live use of the map is still not established.",
        known_drive_id_if_any="1NnYMxq39WObWYIn-1blbuD7uHXon-c-v",
        candidate_ledger_match_if_any=None,
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-W4-CAST",
        referenced_name="Week 4 cast list",
        referenced_from="BCS-000037 and BCS-000053; question week_4_cast_list_absent",
        project_or_family="roanoke-s3-week-operations",
        probable_source_type="cast list",
        why_it_matters="Weeks 1–3 have cast containers. Week 4's breakdown names a cast list and does not link a container. The opened Break down Template candidate is an empty form, not this list.",
        known_drive_id_if_any=None,
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-HEX-DRAWINGS",
        referenced_name="Blind hex grid and transparency copy",
        referenced_from="BCS-000024 remote-play guide",
        project_or_family="roanoke-remote-play-guide",
        probable_source_type="map drawing",
        why_it_matters="The guide's playable map is two drawings, not the Season 3 map key. Season is not established from this guide alone.",
        known_drive_id_if_any="1sBhb99XIowVWrrV0iV4pPyz71As71C1Wuw62Y_gQKfU; 1sSi7z6Uon7xgZggpn8ECTfkkl_-FP0Yjivd7Kt3XZmM",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-W2-AUDIO",
        referenced_name="Week 2 magic-mouth and shriek audio",
        referenced_from="BCS-000029 week 2 breakdown",
        project_or_family="roanoke-s3-week-operations",
        probable_source_type="audio asset",
        why_it_matters="The voice event cites two Drive files for the recording and the creature sound. They are not containers. This does not establish that the event was run.",
        known_drive_id_if_any="1uZ5pgjKy8lxoo-6sZyyZyT8VYdDmovZ3; 1oKdO8L6yzvKSx9SNnbt06ehqfQnbeuA7",
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-REVISION-BODIES",
        referenced_name="Unfetched Google revision bodies",
        referenced_from="sources/**/revisions.jsonl body_fetched false",
        project_or_family="cross-project",
        probable_source_type="revision body",
        why_it_matters="Revision metadata is present and most revision text was not fetched. A researcher can see that a file changed and cannot see what the earlier wording was.",
        known_drive_id_if_any=None,
        candidate_ledger_match_if_any=None,
        status="MISSING_KNOWN_SOURCE",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-SANE-PRICES",
        referenced_name="Sane Magical Prices",
        referenced_from="BCS-000001 Empire City crafting; BCS-000069 directory auxiliary list",
        project_or_family="empire-city-crafting",
        probable_source_type="third-party price table",
        why_it_matters="Crafting math points at this file. It is a circulated reference table, not a missing Brendon design document.",
        known_drive_id_if_any="0B8XAiXpOfz9cMWt1RTBicmpmUDg",
        candidate_ledger_match_if_any=None,
        status="EXTERNAL_OR_UNAVAILABLE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-S3-DIRECTORY-HEADINGS",
        referenced_name="Season 3 directory resource names without URLs",
        referenced_from="BCS-000069 normalized body",
        project_or_family="roanoke-s3-directory",
        probable_source_type="index headings",
        why_it_matters="The directory lists all-hands notes, initiative trackers, week bestiaries, week shops, a week 4 town charter, a macguffin list, week 5 endings, Season 2 charter/crafting/map files, and similar lines. The normalized text has no URLs for them. Some may be sections or links dropped in normalization. They are not each proven to be a separate missing file.",
        known_drive_id_if_any=None,
        candidate_ledger_match_if_any=None,
        status="AMBIGUOUS_REFERENCE",
        confidence="MEDIUM",
    ),
    gap(
        gap_id="GAP-ALMANAC",
        referenced_name="The Arcanian Almanac",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="early Roanoke playtest",
        probable_source_type="setting and race playtest",
        why_it_matters="Current body is BCS-000143, the 2019 almanac playtest. It is earlier context for later race text, not their parent file, and its revision bodies were not fetched.",
        known_drive_id_if_any="1To_48fHi0RuYoeov-qWBXUgSDaB8LN7WkXkX8hJFREI",
        candidate_ledger_match_if_any="ADMITTED BCS-000143",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-ROWING-OAK",
        referenced_name="The Rowing Oak",
        referenced_from="research/source-leads/early-roanoke-rowing-oak-2018.md; registry roanoke-early-2018",
        project_or_family="roanoke-early-2018",
        probable_source_type="campaign architecture",
        why_it_matters="Current export is BCS-000136, the 2019-03-13 state. The July 2018 revision named in the source lead was not fetched.",
        known_drive_id_if_any="11QDOazLzTM3Mv0E4hnPyFpY1wyYweeCoG-ZX8eyX6ho",
        candidate_ledger_match_if_any="ADMITTED BCS-000136",
        status="PARTIAL_CURRENT_BODY_ONLY",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-ROWING-OAK-GUIDE",
        referenced_name="The rowing oak guide.",
        referenced_from="research/source-leads/early-roanoke-rowing-oak-2018.md; registry live-window source_ref",
        project_or_family="roanoke-early-2018",
        probable_source_type="multi-DM operations guide",
        why_it_matters="Prose is BCS-000137. The DOCX export is still rejected as too large, so guide images remain omitted. Earlier revisions were not fetched.",
        known_drive_id_if_any="1JqDKaRTEx89rAUcNrtSg4I6ZD7XAHRkFTWqDRRCroHw",
        candidate_ledger_match_if_any="ADMITTED BCS-000137",
        status="PARTIAL_CURRENT_BODY_ONLY",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-WELLSPRINGS-PHB",
        referenced_name="Wellsprings phb",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="at-wars-end-cosmology",
        probable_source_type="rules companion",
        why_it_matters="BCS-000066 is the novel's wellsprings chapter. The PHB is a separate candidate and may be the system text.",
        known_drive_id_if_any="1g6ZQhzVoAWzFikAoTYJfqUJIyBwMmpgZojidn57tOu0",
        candidate_ledger_match_if_any="UNREVIEWED_CANDIDATE Wellsprings phb",
        status="POSSIBLE_CANDIDATE_MATCH",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-ARCANIA-SETTING-BOOK",
        referenced_name="Arcania Setting Book",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="Arcania setting",
        probable_source_type="setting book",
        why_it_matters="Current body is BCS-000180. It is a short setting introduction, not a finished book in the sense of a complete manuscript, and it is not assigned to a season.",
        known_drive_id_if_any="1Xgtbk9cJqlvwx7lCcRo3EPGuWuYzCd5zOoX_99BPo80",
        candidate_ledger_match_if_any="ADMITTED BCS-000180",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-RACES-ISAKEI",
        referenced_name="Races for the isakei",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="2026 design, project unresolved",
        probable_source_type="later race-reskin notes",
        why_it_matters="Current body is BCS-000189. It is 2026 reskin notes, not a Season 3 source, and it does not replace the verbatims.",
        known_drive_id_if_any="1NIK4fF4Zc676Q9zEWIN0KYjcirS3bTW4N6iSqYCskEg",
        candidate_ledger_match_if_any="ADMITTED BCS-000189",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-BOWLING",
        referenced_name="Bowling Event",
        referenced_from="registry/projects.jsonl bowling-event-2018",
        project_or_family="bowling-event-2018",
        probable_source_type="format experiment",
        why_it_matters="The design document is BCS-000182. The registry creation date stays 2018-08-30. The file does not show the event was held.",
        known_drive_id_if_any="1bn1YBXqQyD22XfbyIme_S-AvBI7hLT92GCC2Jt4f5b4",
        candidate_ledger_match_if_any="ADMITTED BCS-000182",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-LEGENDS-SIGNUP",
        referenced_name="Legends sign up",
        referenced_from="registry/projects.jsonl roanoke-s5-legends planning anchor 2023-04-30",
        project_or_family="roanoke-s5-legends",
        probable_source_type="signup sheet",
        why_it_matters="The signup sheet is BCS-000151. Answers are the respondents' answers. A signup is not attendance.",
        known_drive_id_if_any="12xmsqaB6x09sOn2wBvsWAFpEsAM5fFukKBH5h9eC5UA",
        candidate_ledger_match_if_any="ADMITTED BCS-000151",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-SEASON5-FRAMING",
        referenced_name="Season 5.",
        referenced_from="registry/projects.jsonl; research/CHRONOLOGY.md; research/drive-inventory/2026-10-03/TRIAGE_2026-10-05.md",
        project_or_family="roanoke-s5-legends",
        probable_source_type="season framing",
        why_it_matters="Current body is BCS-000183. It asks which is the greater virtue, justice or mercy. It is not a postmortem and not play.",
        known_drive_id_if_any="1_wqsPUOwI5frqMz0uZ86-cx40pep44hTAxdt4PRCXTA",
        candidate_ledger_match_if_any="ADMITTED BCS-000183",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-FERRYTOWN-SCHEDULE",
        referenced_name="Ferrytown Main Event Schedule",
        referenced_from="BCS-000072 comments.jsonl, comment quoting Schedule",
        project_or_family="roanoke-s4 / empire-city-operations",
        probable_source_type="borough event schedule",
        why_it_matters="The schedule is BCS-000140. The separate Ferrytown master document is BCS-000173. Neither shows that a listed event occurred.",
        known_drive_id_if_any="134nblLb3PbfnnWj72rFstSzA17X39dOKapaFn6s3IEM",
        candidate_ledger_match_if_any="ADMITTED BCS-000140",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-ELEVATOR",
        referenced_name="Elevator Gauntlet",
        referenced_from="BCS-000052 week 3 breakdown",
        project_or_family="roanoke-s3-week-operations",
        probable_source_type="encounter module",
        why_it_matters="The module is BCS-000146. Its pass condition is preparation, not a record that the week was run.",
        known_drive_id_if_any="1fpuTPkVyJzE5n9gxIcBMZ_J3q_mOXHq6uwpCKnKxQGU",
        candidate_ledger_match_if_any="ADMITTED BCS-000146",
        status="RESOLVED",
        confidence="HIGH",
    ),
    gap(
        gap_id="GAP-CORRECTED-HOMEBREWERY",
        referenced_name="Corrected Homebrewery.pdf",
        referenced_from="research/source-leads/homebrew-mechanics-worldbuilding.md",
        project_or_family="UNRESOLVED",
        probable_source_type="homebrew export",
        why_it_matters="Named as a corrected export. Authorship is not established by Drive presence. Do not ingest it as precedent until provenance is checked.",
        known_drive_id_if_any="1r1OUHeNxVIIueMWtsQ7J5xwL2szoHMa5",
        candidate_ledger_match_if_any="UNREVIEWED_CANDIDATE Corrected Homebrewery.pdf",
        status="POSSIBLE_CANDIDATE_MATCH",
        confidence="MEDIUM",
    ),
]


def render(rows: list[dict]) -> str:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    lines = [
        "# Archive-gap ledger — 2026-10-05",
        "",
        "Explicit references only. A directory heading without a URL is one ambiguous row, not a stack of invented files.",
        "",
        "Regenerated from the ledger in this script. A RESOLVED row means the named current body is a container. PARTIAL_CURRENT_BODY_ONLY means that body is present and an earlier wording or omitted export is still missing. A row is not proof the file was re-opened for this regeneration.",
        "",
        "## Counts",
        "",
    ]
    for status in (
        "MISSING_KNOWN_SOURCE",
        "POSSIBLE_CANDIDATE_MATCH",
        "EXTERNAL_OR_UNAVAILABLE",
        "AMBIGUOUS_REFERENCE",
        "PRESENT_UNDER_DIFFERENT_NAME",
        "PARTIAL_CURRENT_BODY_ONLY",
        "RESOLVED",
    ):
        lines.append(f"- `{status}`: {counts.get(status, 0)}")
    lines.extend(["", "## Rows", ""])
    for row in rows:
        lines.append(f"### {row['gap_id']}")
        lines.append("")
        lines.append(f"- Name: {row['referenced_name']}")
        lines.append(f"- Status: `{row['status']}` ({row['confidence']})")
        lines.append(f"- From: {row['referenced_from']}")
        lines.append(f"- Project or family: {row['project_or_family']}")
        lines.append(f"- Type: {row['probable_source_type']}")
        if row["known_drive_id_if_any"]:
            lines.append(f"- Drive id: `{row['known_drive_id_if_any']}`")
        if row["candidate_ledger_match_if_any"]:
            lines.append(f"- Candidate: {row['candidate_ledger_match_if_any']}")
        lines.append(f"- Why it matters: {row['why_it_matters']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".")
    args = parser.parse_args()
    dest = Path(args.repo).resolve() / "research" / "substrate"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "archive_gaps.jsonl").write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in GAPS),
        encoding="utf-8",
    )
    (dest / "archive_gaps.md").write_text(render(GAPS), encoding="utf-8")
    print(len(GAPS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
